export enum ActionType {
    USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST",
    USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR",

    USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST",
    USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS",
    USER_SIGNIN_ERROR = "USER_SIGNIN_ERROR",

    USER_SIGNOUT = 'USER_SIGNOUT',

    EMAIL_CONFIRM_REQUEST = "EMAIL_CONFIRM_REQUEST",
    EMAIL_CONFIRM_SUCCESS = "EMAIL_CONFIRM_SUCCESS",
    EMAIL_CONFIRM_ERROR = "EMAIL_CONFIRM_ERROR",
}